#!/usr/bin/bash
# displays domain and subdomains

display_domain_subdomain () {
dig "$1" +short | awk -v subdomain="$2" 'NR==1 { print "The subdomain " subdomain " is a A record and points to " $1 }'
}
if [ "$#" -eq 2 ]
then
	display_domain_subdomain "$2.$1" "$2"
else
	display_domain_subdomain "www.$1" "www"
	display_domain_subdomain "lb-01.$1" "lb-01"
	display_domain_subdomain "web-01.$1" "web-01"
	display_domain_subdomain "web-02.$1" "web-02"
fi
