#!/usr/bin/env bash
# configuration of my Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y upgrade

# Installation of Nginx
sudo apt-get install -y nginx
sudo ifw allow 'Nginx HTTP'

# modify default Nginx configuration to return "Hello World!" at root URL
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/@pury8351 permanent;' /etc/nginx/sites-available/default
# Restart Nginx without using systemctl
sudo service nginx restart
