#!/usr/bin/env bash
# Configures HAproxy so that it send traffic to web-01 and web-02 using roundrobin algorithm

# Package lists update and HAproxy installation
sudo apt-get update
sudo apt-get install -y haproxy

# Back up original configuration file
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# new configuration file
sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
global
	log /dev/log local0
	log /dev/log local1 notice
	chroot /var/lib/haproxy
	sats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log global
	mode http
	option httplog
	option dontlognull
	timeout connect 5000
	timeout client 50000
	timeout server 50000

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server web-01 54.172.115.20
	server web-02 54.208.24.146
EOF
'
# Enable and start HAProxy configuration
sudo systemctl enable haproxy
sudo systemctl start haproxy

#restart HAProxy to apply configuration changes
sudo systemctl restart haproxy
