#!/usr/bin/env bash
# Configures HAproxy so that it send traffic to web-01 and web-02 using roundrobin algorithm

# Package lists update and HAproxy installation
sudo apt-get update -y
sudo apt-get install -y haproxy

# Back up original configuration file
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# new configuration file
sudo bash -c 'cat <<EOF > /etc/haproxy/haproxy.cfg
defaults
	log global
	mode http
	option httplog
	option dontlognull
	timeout connect 5000
	timeout client 50000
	timeout server 50000

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server 495515-web-01 54.172.115.20:80 check
	server 495515-web-02 54.208.24.146:80 check
EOF
'
# Enable and start HAProxy configuration
sudo systemctl enable haproxy.service

#restart HAProxy to apply configuration changes
sudo systemctl restart haproxy.service
