#!/usr/bin/env bash
# steps to ensure Nginx is running and listening on port 80

sudo apt-get update -y
sudo apt-get install -y nginx
sudo systemctl enable nginx

sudo tee /etc/nginx/sites-available/default <<EOL
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
	try_files \$uri \$uri/  =404
	}
}
EOL

sudo systemctl start nginx
