#!/bin/bash
-rwxr--r-- 1 root root 66 Aug  4 03:36 0-current_working_directory
-rwxr--r-- 1 root root 59 Aug  4 02:50 1-listit
-rwxr--r-- 1 root root 21 Aug  4 03:31 2-bring_me_home
-rwxr--r-- 1 root root 13 Aug  4 03:30 3-listfiles
-rwxr--r-- 1 root root 51 Aug  4 02:40 README.md
