#!/usr/bin/env bash
# displays "Best School" 10 times, adds Hi for the 9th

i=0
while [ "$i" -lt 10 ]
do
  if [ "$i" -eq 8 ] # find the 9th iteration
  then
	  echo "Best School"
	  echo "Hi"
  else
	  echo "Best School"
  fi
 ((i++)) # Increment i after each iteration
done
