#!/usr/bin/env bash
# debugging docker to have Apache return a page containing Hello Holberton when quering the root of it

sudo apt-get  update -y
sudo  apt-get install -y apache2

# start apache2 service
sudo service apache2 start

# Ensure Apache starts on boot
sudo sytemctl enable apache2

#confirm apache2 is running and print message
if sudo service apache2 status |grep -q "running"; then
	echo "apache2 is running"
fi

#confirm apache2 is running
sudo service apache2 status

echo "Hello Holberton" | tee -a /var/www/html/index.html

sudo /etc/init.d/apache2 restart 
