#!/usr/bin/env bash
# debugging docker to have Apache return a page containing Hello Holberton when quering the root of it

sudo apt-get  update -y
sudo  apt-get install -y apache2
sudo /etc/init.d/apache2 start

# check if apache2 is running and output results
if sudo /etc/init.d/apache2 status | grep -q "running"; then
	echo "apache2 is running"
fi

echo "Hello Holberton" | tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart 
