#!/usr/bin/env bash
# script that uses ssh to connect to my server
# uses private key ~/.ssh/school witht he user ubuntu

server="54.172.115.20"

#SSH connection using single-character flags
ssh -i ~/.ssh/school -o
ubuntu@$server
