#!/usr/bin/env bash
# creates RSA key pair,with private key as "school", 4096 bits
# and passphrase "betty"

key_name="school"
key_path="home/.ssh/$key_name"
passphrase="betty"
key_bits=4096

# make directory if it doesn't exist
mkdir -p "home/.ssh"

# Generate RSA key pair
ssh-keygen -t rsa -b "$key_bits" -f "$key_path" -N "$passphrase"
