#!/usr/bin/env bash
# creates RSA key pair,with private key as "school", 4096 bits
# and passphrase "betty"

# create directory if not exists
mkdir -p "~/.ssh/"

cd ~/.ssh
# create key
ssh-keygen -t rsa -b 4096 -f "school" -N "betty"
